export const tags = [
    'asymmetric',
    'analyzer',
    'hierarchy',
    'bandwidth-monitored',
    'non-volatile',
    'User-centric',
    'open architecture',
    'Up-sized',
    'groupware',
    'static',
    'forecast',
    'Team-oriented',
    'Sharable',
    'artificial intelligence',
    'Decentralized',
    'Reduced',
    'firmware',
    'User-friendly',
    'holistic',
    'portal',
    'Persistent',
    'multi-tasking',
    'flexibility',
    'Public-key',
    'Reactive',
    'Stand-alone',
    'modular',
    'heuristic',
    'Exclusive',
    'even-keeled',
    'success',
    'attitude',
    'Horizontal',
    'Integrated',
    'multi-tasking',
    'Ameliorated',
    'Open-architected'
]

export const persons = [
    'Dore Maccrae',
    'Ransom Osbidston',
    'Eduardo Guilder',
    'Waylan Hallbord',
    'Lacie Scandroot',
    'Henrieta Skerme',
    'Tuckie Wandless',
    'Brook Rea',
    'Deonne Girardetti',
    'Modestia Heavy',
    'Janella Doerr',
    'Rodi Agius',
    'Umberto Ventris',
    'Madison Mineghelli',
    'Audrye McVitie',
    'Petronia Molloy',
    'Lilas Peacocke',
    'Lexi Cazin',
    'Doloritas Litchmore',
    'Danice Brockett',
    'Kennith McCrillis',
    'Evaleen Hayden',
    'Packston Tourot'
]

export const ideas = [
    'He turned in the research paper on Friday; otherwise, he would have not passed the class.',
    'Christmas is coming.',
    'Where do random thoughts come from?',
    'A purple pig and a green donkey flew a kite in the middle of the night and ended up sunburnt.',
    'Joe made the sugar cookies; Susan decorated them.',
    'They got there early, and they got really good seats.',
    'The sky is clear; the stars are twinkling.',
    'Lets all be unique together until we realise we are all the same.',
    'The book is in front of the table.',
    'What was the person thinking when they discovered cow’s milk was fine for human consumption… and why did they do it in the first place!?',
    'This is a Japanese doll.',
    'The lake is a long way from here.',
    'The mysterious diary records the voice.',
    'Wow, does that work?',
    'The stranger officiates the meal.',
    'Two seats were vacant.',
    'I was very proud of my nickname throughout high school but today- I couldn’t be any different to what my nickname was.',
    'Should we start class now, or should we wait for everyone to get here?',
    'The body may perhaps compensates for the loss of a true metaphysics.',
    'We have a lot of rain in June.',
    'She only paints with bold colors; she does not like pastels.',
    'The river stole the gods.',
    'The quick brown fox jumps over the lazy dog.',
    'Mary plays the piano.',
    "A song can make or ruin a person’s day if they let it get to them.",
    'The old apple revels in its authority.',
    'I am never at home on Sundays.',
    'I am happy to take your donation; any amount will be greatly appreciated.',
    'I really want to go to work, but I am too sick to drive.',
    'Abstraction is often one floor above you.',
    'Rock music approaches at high velocity.',
    'He told us a very exciting adventure story.',
    'This is the last random sentence I will be writing and I am going to stop mid-sent',
    'Let me help you with your baggage.',
    'Hurry!',
    'She did her best to help him.',
    'Cats are good pets, for they are clean and are not noisy.',
    "I'd rather be a bird than a fish.",
    'If Purple People Eaters are real… where do they find purple people to eat?',
    "He didn’t want to go to the dentist, yet he went anyway.",
    'I want to buy a onesie… but know it won’t suit me.',
    'I checked to make sure that he was still alive.',
    'Malls are great places to shop; I can find everything I need under one roof.',
    'When I was little I had a car door slammed shut on my hand. I still remember it quite vividly.',
    'Italy is my favorite country; in fact, I plan to spend two weeks there next year.',
    'I think I will buy the red car, or I will lease the blue one.',
    'Everyone was busy, so I went to the movie alone.',
    'I will never be this young again. Ever. Oh damn… I just got older.',
    "I would have gotten the promotion, but my attendance wasn’t good enough."
]

